### ISSUE TITLE
Confusing Documentation: `return nothing`/self.render

### ISSUE THREAD

**Issue by zoffixznet** [ufobat/Bailador#74]
In the docs for [route return values](https://github.com/ufobat/Bailador#return-values-of-routes) it says `Return Nothing ...` what exactly is *Nothing*? Even a `sub{}()` returns a `Nil`. If you mean `Nil` for `Nothing`, then explicitly using `Nil` avoids confusion.

Also in the same section for Nothing/Something, it's unclear: How do I render something? I see `self.render` mentioned, but what do I use if I'm using the subs approach?

**Comment by ufobat** [comment]
Thanks for the feedback. with `nothing` i mean something thats is not `defined`. Thats the place in the  [code](https://github.com/ufobat/Bailador/blob/master/lib/Bailador/App.pm#L88). I will update the documentation.

If you return something in the sub
> this will be the content of the response.
by that i mean this will be rendered. 
> as long as you don't have rendered something in the callable of the route. Using `self.render` will turn of auto rendering.
with `auto rendering` i mean that the result of the sub automatically gets rendered.
since you did not (because you can not) call `self.render`, auto rendering is not turned off.

so far there is no way of calling `self.render` in the subs approach, but i think this could be turned on easily if we change the `sub app()` to be exported.

**Comment by ufobat** [comment]
I hope this commit makes the readme a bit more understandable?
https://github.com/ufobat/Bailador/commit/9412e506a0fd0d9f9caea57dcbf0f7cc6ebb9767

**Comment by zoffixznet** [comment]
Looks good. Thanks.
